/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fadila Nur Habibah
 */
public class Desain extends javax.swing.JFrame {
     private String username;

    /**
     * Creates new form Desain
     */
    public Desain() {
        initComponents();
        load_data1();
        this.dispose(); 
    }
    
    public JTabbedPane getTabbedPane() {
        return tab;
    }
    
    public JTable getTabelPelanggan() {
    return jTable1; // ganti 'tabelPelanggan' dengan nama JTable di tab ke-3
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        tab = new raven.tabbed.TabbedPaneCustom();
        panelKategori = new javax.swing.JPanel();
        panelJudulKategori = new javax.swing.JPanel();
        buttonEdukasi = new rojerusan.RSMaterialButtonRectangle();
        buttonProfil = new rojerusan.RSMaterialButtonRectangle();
        Kategori1 = new untukpraktikum5.GradientRoundedPanel();
        panelEdukasi = new untukpraktikum5.GradientRoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelLifeStyle = new untukpraktikum5.GradientRoundedPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        panelKatalog = new javax.swing.JPanel();
        Katalog = new untukpraktikum5.GradientRoundedPanel();
        katalog1 = new javax.swing.JLabel();
        katalogJarik = new rojerusan.RSMaterialButtonRectangle();
        katalog2 = new javax.swing.JLabel();
        katalogJaket = new rojerusan.RSMaterialButtonRectangle();
        katalog3 = new javax.swing.JLabel();
        katalogDress = new rojerusan.RSMaterialButtonRectangle();
        katalog4 = new javax.swing.JLabel();
        katalogVest = new rojerusan.RSMaterialButtonRectangle();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelRiwayat = new javax.swing.JPanel();
        panelNavyRiwayat = new javax.swing.JPanel();
        panelTabel = new untukpraktikum5.GradientRoundedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelEvent = new javax.swing.JPanel();
        gradientRoundedPanel3 = new untukpraktikum5.GradientRoundedPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelCRUD = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        eventKeterangan = new javax.swing.JTextField();
        eventCari = new javax.swing.JTextField();
        eventTempat = new javax.swing.JTextField();
        eventJenis = new javax.swing.JTextField();
        btnHapus = new rojerusan.RSMaterialButtonRectangle();
        btnSimpan = new rojerusan.RSMaterialButtonRectangle();
        btnEdit = new rojerusan.RSMaterialButtonRectangle();
        jLabel27 = new javax.swing.JLabel();
        eventNama = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        eventID = new javax.swing.JTextField();
        btnCari = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));

        tab.setBackground(new java.awt.Color(204, 204, 255));
        tab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tab.setSelectedColor(new java.awt.Color(0, 0, 102));

        panelKategori.setLayout(null);

        panelJudulKategori.setBackground(new java.awt.Color(255, 255, 255));

        buttonEdukasi.setBackground(new java.awt.Color(255, 153, 153));
        buttonEdukasi.setText("E D U K A S I");
        buttonEdukasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdukasiActionPerformed(evt);
            }
        });

        buttonProfil.setBackground(new java.awt.Color(153, 153, 255));
        buttonProfil.setText("L I F E   S T Y L E");
        buttonProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJudulKategoriLayout = new javax.swing.GroupLayout(panelJudulKategori);
        panelJudulKategori.setLayout(panelJudulKategoriLayout);
        panelJudulKategoriLayout.setHorizontalGroup(
            panelJudulKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudulKategoriLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(buttonEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(buttonProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        panelJudulKategoriLayout.setVerticalGroup(
            panelJudulKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJudulKategoriLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelJudulKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelKategori.add(panelJudulKategori);
        panelJudulKategori.setBounds(0, 0, 1240, 140);

        Kategori1.setColorStart(new java.awt.Color(255, 153, 153));
        Kategori1.setLayout(new java.awt.CardLayout());

        panelEdukasi.setColorStart(new java.awt.Color(255, 153, 153));
        panelEdukasi.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi1.png"))); // NOI18N
        panelEdukasi.add(jLabel1);
        jLabel1.setBounds(40, 80, 240, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi2.png"))); // NOI18N
        panelEdukasi.add(jLabel2);
        jLabel2.setBounds(40, 300, 240, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi3.png"))); // NOI18N
        panelEdukasi.add(jLabel3);
        jLabel3.setBounds(330, 80, 230, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi6.png"))); // NOI18N
        panelEdukasi.add(jLabel4);
        jLabel4.setBounds(330, 300, 230, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi8.png"))); // NOI18N
        panelEdukasi.add(jLabel5);
        jLabel5.setBounds(620, 80, 240, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi7.png"))); // NOI18N
        panelEdukasi.add(jLabel6);
        jLabel6.setBounds(620, 300, 240, 180);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi4.png"))); // NOI18N
        panelEdukasi.add(jLabel7);
        jLabel7.setBounds(920, 80, 230, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Edukasi/edukasi5.png"))); // NOI18N
        panelEdukasi.add(jLabel8);
        jLabel8.setBounds(920, 300, 230, 180);

        Kategori1.add(panelEdukasi, "card2");

        panelLifeStyle.setColorEnd(new java.awt.Color(153, 153, 255));
        panelLifeStyle.setColorStart(new java.awt.Color(102, 102, 255));
        panelLifeStyle.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle5.png"))); // NOI18N
        panelLifeStyle.add(jLabel19);
        jLabel19.setBounds(1000, 50, 160, 210);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle10.png"))); // NOI18N
        panelLifeStyle.add(jLabel21);
        jLabel21.setBounds(650, 310, 140, 210);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle8.png"))); // NOI18N
        panelLifeStyle.add(jLabel22);
        jLabel22.setBounds(890, 260, 170, 260);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle4.png"))); // NOI18N
        panelLifeStyle.add(jLabel23);
        jLabel23.setBounds(530, 40, 140, 210);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle1.png"))); // NOI18N
        panelLifeStyle.add(jLabel29);
        jLabel29.setBounds(70, 40, 140, 210);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle6.png"))); // NOI18N
        panelLifeStyle.add(jLabel30);
        jLabel30.setBounds(430, 300, 140, 210);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle7.png"))); // NOI18N
        panelLifeStyle.add(jLabel31);
        jLabel31.setBounds(510, 300, 140, 210);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle3.png"))); // NOI18N
        panelLifeStyle.add(jLabel32);
        jLabel32.setBounds(770, 40, 140, 210);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle11.png"))); // NOI18N
        panelLifeStyle.add(jLabel33);
        jLabel33.setBounds(580, 310, 120, 210);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle2.png"))); // NOI18N
        panelLifeStyle.add(jLabel34);
        jLabel34.setBounds(300, 40, 140, 210);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lifeStyle/lifeStyle9.png"))); // NOI18N
        panelLifeStyle.add(jLabel28);
        jLabel28.setBounds(190, 280, 170, 230);

        Kategori1.add(panelLifeStyle, "card2");

        panelKategori.add(Kategori1);
        Kategori1.setBounds(0, 140, 1240, 560);

        tab.addTab("KATEGORI", panelKategori);

        panelKatalog.setBackground(new java.awt.Color(255, 255, 255));
        panelKatalog.setLayout(null);

        Katalog.setColorEnd(new java.awt.Color(153, 153, 255));
        Katalog.setColorStart(new java.awt.Color(255, 153, 153));
        Katalog.setLayout(null);

        katalog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Katalog/katalog1.png"))); // NOI18N
        Katalog.add(katalog1);
        katalog1.setBounds(80, 170, 190, 200);

        katalogJarik.setBackground(new java.awt.Color(255, 255, 255));
        katalogJarik.setForeground(new java.awt.Color(0, 0, 0));
        katalogJarik.setText("Show  More");
        katalogJarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katalogJarikActionPerformed(evt);
            }
        });
        Katalog.add(katalogJarik);
        katalogJarik.setBounds(940, 380, 200, 70);

        katalog2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Katalog/katalog2.png"))); // NOI18N
        Katalog.add(katalog2);
        katalog2.setBounds(360, 170, 180, 200);

        katalogJaket.setBackground(new java.awt.Color(255, 255, 255));
        katalogJaket.setForeground(new java.awt.Color(0, 0, 0));
        katalogJaket.setText("Show  More");
        katalogJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katalogJaketActionPerformed(evt);
            }
        });
        Katalog.add(katalogJaket);
        katalogJaket.setBounds(70, 380, 210, 70);

        katalog3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Katalog/katalog4.png"))); // NOI18N
        Katalog.add(katalog3);
        katalog3.setBounds(650, 170, 180, 190);

        katalogDress.setBackground(new java.awt.Color(255, 255, 255));
        katalogDress.setForeground(new java.awt.Color(0, 0, 0));
        katalogDress.setText("Show  More");
        katalogDress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katalogDressActionPerformed(evt);
            }
        });
        Katalog.add(katalogDress);
        katalogDress.setBounds(350, 380, 200, 70);

        katalog4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Katalog/katalog3.png"))); // NOI18N
        Katalog.add(katalog4);
        katalog4.setBounds(950, 170, 180, 200);

        katalogVest.setBackground(new java.awt.Color(255, 255, 255));
        katalogVest.setForeground(new java.awt.Color(0, 0, 0));
        katalogVest.setText("Show  More");
        katalogVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                katalogVestActionPerformed(evt);
            }
        });
        Katalog.add(katalogVest);
        katalogVest.setBounds(640, 380, 200, 70);

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel9.setText("-- Batik Jacket --");
        Katalog.add(jLabel9);
        jLabel9.setBounds(80, 130, 180, 33);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel10.setText("-- Batik Jarik --");
        Katalog.add(jLabel10);
        jLabel10.setBounds(960, 130, 170, 33);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel11.setText("-- Batik Dress --");
        Katalog.add(jLabel11);
        jLabel11.setBounds(360, 130, 173, 33);

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 3, 24)); // NOI18N
        jLabel12.setText("-- Batik Vest --");
        Katalog.add(jLabel12);
        jLabel12.setBounds(660, 130, 160, 33);

        panelKatalog.add(Katalog);
        Katalog.setBounds(0, 140, 1240, 560);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 80)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("KATALOG BATIK");
        panelKatalog.add(jLabel17);
        jLabel17.setBounds(270, 20, 650, 70);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 80)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 153));
        jLabel18.setText("KATALOG BATIK");
        panelKatalog.add(jLabel18);
        jLabel18.setBounds(280, 20, 650, 70);

        tab.addTab("KATALOG BATIK", panelKatalog);

        panelNavyRiwayat.setBackground(new java.awt.Color(0, 0, 102));
        panelNavyRiwayat.setLayout(null);

        panelTabel.setColorEnd(new java.awt.Color(153, 153, 255));
        panelTabel.setColorStart(new java.awt.Color(255, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        panelNavyRiwayat.add(panelTabel);
        panelTabel.setBounds(0, 150, 1220, 580);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 50)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Catatan Pembelian");
        panelNavyRiwayat.add(jLabel13);
        jLabel13.setBounds(360, 20, 460, 67);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 50)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 102));
        jLabel14.setText("Yuk, Intip Kembali!");
        panelNavyRiwayat.add(jLabel14);
        jLabel14.setBounds(360, 70, 470, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pembayaran/pembayaran4.png"))); // NOI18N
        panelNavyRiwayat.add(jLabel15);
        jLabel15.setBounds(850, 50, 320, 60);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pembayaran/pembayaran4.png"))); // NOI18N
        panelNavyRiwayat.add(jLabel16);
        jLabel16.setBounds(20, 40, 320, 70);

        javax.swing.GroupLayout panelRiwayatLayout = new javax.swing.GroupLayout(panelRiwayat);
        panelRiwayat.setLayout(panelRiwayatLayout);
        panelRiwayatLayout.setHorizontalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNavyRiwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1233, Short.MAX_VALUE)
        );
        panelRiwayatLayout.setVerticalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRiwayatLayout.createSequentialGroup()
                .addComponent(panelNavyRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        tab.addTab("RIWAYAT PEMBELI", panelRiwayat);

        gradientRoundedPanel3.setColorEnd(new java.awt.Color(153, 153, 255));
        gradientRoundedPanel3.setColorStart(new java.awt.Color(255, 153, 153));
        gradientRoundedPanel3.setLayout(null);

        jScrollPane3.setEnabled(false);

        tabelCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCRUD.setEnabled(false);
        tabelCRUD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCRUDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelCRUD);

        gradientRoundedPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(70, 160, 610, 350);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 255));
        jLabel35.setText("Beri Tahu Yang Lain ");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 153, 153));
        jLabel36.setText("EVENT KAMI !!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        gradientRoundedPanel3.add(jPanel5);
        jPanel5.setBounds(0, 0, 1240, 120);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setText("CARI");
        gradientRoundedPanel3.add(jLabel20);
        jLabel20.setBounds(880, 150, 60, 32);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setText("TEMPAT EVENT");
        gradientRoundedPanel3.add(jLabel24);
        jLabel24.setBounds(720, 350, 130, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setText("JENIS EVENT");
        gradientRoundedPanel3.add(jLabel25);
        jLabel25.setBounds(720, 402, 110, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setText("KETERANGAN");
        gradientRoundedPanel3.add(jLabel26);
        jLabel26.setBounds(720, 450, 110, 22);
        gradientRoundedPanel3.add(eventKeterangan);
        eventKeterangan.setBounds(880, 450, 230, 30);
        gradientRoundedPanel3.add(eventCari);
        eventCari.setBounds(720, 200, 390, 30);
        gradientRoundedPanel3.add(eventTempat);
        eventTempat.setBounds(880, 350, 230, 30);
        gradientRoundedPanel3.add(eventJenis);
        eventJenis.setBounds(880, 400, 230, 30);

        btnHapus.setText("H A P U S");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gradientRoundedPanel3.add(btnHapus);
        btnHapus.setBounds(660, 590, 170, 60);

        btnSimpan.setText("S I M P A N");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        gradientRoundedPanel3.add(btnSimpan);
        btnSimpan.setBounds(130, 590, 170, 60);

        btnEdit.setText("E D I T");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        gradientRoundedPanel3.add(btnEdit);
        btnEdit.setBounds(400, 590, 170, 60);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setText("NAMA EVENT");
        gradientRoundedPanel3.add(jLabel27);
        jLabel27.setBounds(720, 300, 110, 30);
        gradientRoundedPanel3.add(eventNama);
        eventNama.setBounds(880, 300, 230, 30);

        id.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        id.setText("ID EVENT");
        gradientRoundedPanel3.add(id);
        id.setBounds(720, 260, 110, 30);
        gradientRoundedPanel3.add(eventID);
        eventID.setBounds(880, 250, 230, 30);

        btnCari.setText("C A R I");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        gradientRoundedPanel3.add(btnCari);
        btnCari.setBounds(930, 590, 170, 60);

        javax.swing.GroupLayout panelEventLayout = new javax.swing.GroupLayout(panelEvent);
        panelEvent.setLayout(panelEventLayout);
        panelEventLayout.setHorizontalGroup(
            panelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradientRoundedPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEventLayout.setVerticalGroup(
            panelEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEventLayout.createSequentialGroup()
                .addComponent(gradientRoundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        tab.addTab("EVENT", panelEvent);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEdukasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdukasiActionPerformed
        // TODO add your handling code here:
        Kategori1.removeAll();
        Kategori1.repaint();
        Kategori1.revalidate();
        
        Kategori1.add(panelEdukasi);
        Kategori1.repaint();
        Kategori1.revalidate();
    }//GEN-LAST:event_buttonEdukasiActionPerformed

    private void buttonProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfilActionPerformed
        // TODO add your handling code here:
        Kategori1.removeAll();
        Kategori1.repaint();
        Kategori1.revalidate();
        
        Kategori1.add(panelLifeStyle);
        Kategori1.repaint();
        Kategori1.revalidate();
    }//GEN-LAST:event_buttonProfilActionPerformed

    private void katalogJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katalogJaketActionPerformed
        // TODO add your handling code here:
        jaketNew jaket = new jaketNew ();
        jaket.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_katalogJaketActionPerformed

    private void katalogDressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katalogDressActionPerformed
        // TODO add your handling code here:
        dressNew dress = new dressNew ();
        dress.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_katalogDressActionPerformed

    private void katalogVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katalogVestActionPerformed
        // TODO add your handling code here:
        vestNew vest = new vestNew ();
        vest.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_katalogVestActionPerformed

    private void katalogJarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_katalogJarikActionPerformed
        // TODO add your handling code here:
        jarikNew jarik = new jarikNew ();
        jarik.setVisible(true);    
        this.dispose();
    }//GEN-LAST:event_katalogJarikActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            if (eventID.getText().isEmpty() ||eventNama.getText().isEmpty() || eventTempat.getText().isEmpty() || eventJenis.getText().isEmpty() || eventKeterangan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua data!");
                return; 
            }
            
            String sql = "INSERT INTO event (id, nama, tempat, jenis, ket) VALUES (?, ?, ?, ?, ?)";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, eventID.getText());
            pst.setString(2, eventNama.getText());
            pst.setString(3, eventTempat.getText());
            pst.setString(4, eventJenis.getText());
            pst.setString(5, eventKeterangan.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            load_data1();
            kosong1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }  
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menyimpan perubahan data ini?", "Konfirmasi Perubahan", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String sql = "UPDATE event SET nama = ?, tempat = ?, jenis = ?, ket = ? WHERE id = ?";
                java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, eventNama.getText());
                pst.setString(2, eventTempat.getText());
                pst.setString(3, eventJenis.getText());
                pst.setString(4, eventKeterangan.getText());
                pst.setString(5, eventID.getText());

                int rowsUpdated = pst.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diupdate");
                }

                load_data1(); 
                kosong1();     
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            String id = eventID.getText();

            if (id.isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID belum dipilih. Silakan pilih data terlebih dahulu.");
            } else {
                int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    String sql = "DELETE FROM event WHERE id = ?";
                    java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setString(1, id);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    load_data1();
                    kosong1();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelCRUDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCRUDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelCRUDMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        try {
            load_data1(); 
            String sql = "SELECT * FROM event WHERE id = ?";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, eventCari.getText());
            java.sql.ResultSet res = pst.executeQuery();

            if (res.next()) {
                eventID.setText(res.getString("id"));
                eventNama.setText(res.getString("nama"));
                eventTempat.setText(res.getString("tempat"));
                eventJenis.setText(res.getString("jenis"));
                eventKeterangan.setText(res.getString("ket"));
            } else {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void load_data1() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Tempat");
        model.addColumn("Jenis");
        model.addColumn("Keterangan");

        try {
            String sql = "SELECT * FROM event";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            int no = 1;
            while (res.next()) {
                model.addRow(new Object[]{
//                    no++,
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("tempat"),
                    res.getString("jenis"),
                    res.getString("ket")
                });
            }
            tabelCRUD.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void kosong1(){
        eventID.setText("");
        eventNama.setText("");
        eventTempat.setText("");
        eventJenis.setText("");
        eventKeterangan.setText("");
        eventCari.setText("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private untukpraktikum5.GradientRoundedPanel Katalog;
    private untukpraktikum5.GradientRoundedPanel Kategori1;
    private rojerusan.RSMaterialButtonRectangle btnCari;
    private rojerusan.RSMaterialButtonRectangle btnEdit;
    private rojerusan.RSMaterialButtonRectangle btnHapus;
    private rojerusan.RSMaterialButtonRectangle btnSimpan;
    private rojerusan.RSMaterialButtonRectangle buttonEdukasi;
    private rojerusan.RSMaterialButtonRectangle buttonProfil;
    private javax.swing.JTextField eventCari;
    private javax.swing.JTextField eventID;
    private javax.swing.JTextField eventJenis;
    private javax.swing.JTextField eventKeterangan;
    private javax.swing.JTextField eventNama;
    private javax.swing.JTextField eventTempat;
    private untukpraktikum5.GradientRoundedPanel gradientRoundedPanel3;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel katalog1;
    private javax.swing.JLabel katalog2;
    private javax.swing.JLabel katalog3;
    private javax.swing.JLabel katalog4;
    private rojerusan.RSMaterialButtonRectangle katalogDress;
    private rojerusan.RSMaterialButtonRectangle katalogJaket;
    private rojerusan.RSMaterialButtonRectangle katalogJarik;
    private rojerusan.RSMaterialButtonRectangle katalogVest;
    private untukpraktikum5.GradientRoundedPanel panelEdukasi;
    private javax.swing.JPanel panelEvent;
    private javax.swing.JPanel panelJudulKategori;
    private javax.swing.JPanel panelKatalog;
    private javax.swing.JPanel panelKategori;
    private untukpraktikum5.GradientRoundedPanel panelLifeStyle;
    private javax.swing.JPanel panelNavyRiwayat;
    private javax.swing.JPanel panelRiwayat;
    private untukpraktikum5.GradientRoundedPanel panelTabel;
    private javax.swing.JPanel panelUtama;
    private raven.tabbed.TabbedPaneCustom tab;
    private javax.swing.JTable tabelCRUD;
    // End of variables declaration//GEN-END:variables
}
