/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.event.KeyEvent;

/**
 *
 * @author Fadila Nur Habibah
 */
public class dressNew extends javax.swing.JFrame {

    /**
     * Creates new form dressNew
     */
    public dressNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelJaket = new untukpraktikum5.GradientRoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        backJaket = new rojerusan.RSMaterialButtonRectangle();
        dress2 = new javax.swing.JRadioButton();
        dress4 = new javax.swing.JRadioButton();
        dress1 = new javax.swing.JRadioButton();
        dress6 = new javax.swing.JRadioButton();
        dress3 = new javax.swing.JRadioButton();
        dress5 = new javax.swing.JRadioButton();
        bayarDress = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFdress1 = new javax.swing.JTextField();
        TFdress2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TFdress3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TFdress4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TFdress5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TFdress6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(903, 1563));

        panelJaket.setColorEnd(new java.awt.Color(153, 153, 255));
        panelJaket.setColorStart(new java.awt.Color(255, 153, 153));
        panelJaket.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress2.png"))); // NOI18N
        panelJaket.add(jLabel3);
        jLabel3.setBounds(350, 560, 190, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress6.png"))); // NOI18N
        panelJaket.add(jLabel4);
        jLabel4.setBounds(650, 560, 170, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress5.png"))); // NOI18N
        panelJaket.add(jLabel5);
        jLabel5.setBounds(350, 210, 190, 190);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress1.png"))); // NOI18N
        panelJaket.add(jLabel6);
        jLabel6.setBounds(70, 210, 190, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress3.png"))); // NOI18N
        panelJaket.add(jLabel7);
        jLabel7.setBounds(630, 210, 190, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionDress/dress4.png"))); // NOI18N
        panelJaket.add(jLabel8);
        jLabel8.setBounds(70, 560, 190, 190);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Traditional from Indonesia");
        panelJaket.add(jLabel9);
        jLabel9.setBounds(640, 420, 170, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Rp 425.000");
        panelJaket.add(jLabel12);
        jLabel12.setBounds(120, 450, 80, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Rp 378.000");
        panelJaket.add(jLabel16);
        jLabel16.setBounds(680, 450, 80, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Rp 415.000");
        panelJaket.add(jLabel20);
        jLabel20.setBounds(130, 810, 90, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Rp 375.000");
        panelJaket.add(jLabel24);
        jLabel24.setBounds(410, 810, 100, 20);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Rp 278.000");
        panelJaket.add(jLabel28);
        jLabel28.setBounds(710, 810, 80, 20);

        backJaket.setBackground(new java.awt.Color(0, 0, 102));
        backJaket.setText("B A C K");
        backJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJaketActionPerformed(evt);
            }
        });
        panelJaket.add(backJaket);
        backJaket.setBounds(150, 930, 240, 70);

        dress2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress2.setText("Long Dress Merah Coksu");
        panelJaket.add(dress2);
        dress2.setBounds(320, 400, 240, 30);

        dress4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress4.setText("Long Dress Biru ");
        dress4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dress4ActionPerformed(evt);
            }
        });
        panelJaket.add(dress4);
        dress4.setBounds(80, 750, 170, 30);

        dress1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress1.setText("Long Dress Maroon Hitam");
        dress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dress1ActionPerformed(evt);
            }
        });
        panelJaket.add(dress1);
        dress1.setBounds(30, 400, 250, 30);

        dress6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress6.setText("Long Dress Hitam Hijau");
        panelJaket.add(dress6);
        dress6.setBounds(620, 750, 240, 30);

        dress3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress3.setText("Dress Outer Hitam");
        dress3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dress3ActionPerformed(evt);
            }
        });
        panelJaket.add(dress3);
        dress3.setBounds(630, 400, 180, 30);

        dress5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dress5.setText("Long Dress Hitam Coklat");
        panelJaket.add(dress5);
        dress5.setBounds(330, 750, 240, 30);

        bayarDress.setBackground(new java.awt.Color(0, 0, 102));
        bayarDress.setText("B A Y A R");
        bayarDress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarDressActionPerformed(evt);
            }
        });
        panelJaket.add(bayarDress);
        bayarDress.setBounds(490, 930, 240, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 60)); // NOI18N
        jLabel1.setText("BATIK DRESS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 40, 440, 110);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/home1.png"))); // NOI18N
        jPanel2.add(jLabel32);
        jLabel32.setBounds(570, 0, 210, 170);

        panelJaket.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 160);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("JUMLAH");
        panelJaket.add(jLabel10);
        jLabel10.setBounds(70, 480, 80, 30);

        TFdress1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress1KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress1);
        TFdress1.setBounds(160, 480, 90, 30);

        TFdress2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress2KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress2);
        TFdress2.setBounds(440, 480, 90, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("JUMLAH");
        panelJaket.add(jLabel14);
        jLabel14.setBounds(350, 480, 80, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("JUMLAH");
        panelJaket.add(jLabel18);
        jLabel18.setBounds(640, 480, 80, 30);

        TFdress3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress3KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress3);
        TFdress3.setBounds(730, 480, 90, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("JUMLAH");
        panelJaket.add(jLabel22);
        jLabel22.setBounds(80, 840, 80, 30);

        TFdress4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress4KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress4);
        TFdress4.setBounds(170, 840, 90, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("JUMLAH");
        panelJaket.add(jLabel26);
        jLabel26.setBounds(360, 840, 80, 30);

        TFdress5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress5KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress5);
        TFdress5.setBounds(450, 840, 90, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("JUMLAH");
        panelJaket.add(jLabel30);
        jLabel30.setBounds(650, 840, 80, 30);

        TFdress6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFdress6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFdress6KeyTyped(evt);
            }
        });
        panelJaket.add(TFdress6);
        TFdress6.setBounds(740, 840, 90, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Rp390.000");
        panelJaket.add(jLabel33);
        jLabel33.setBounds(400, 450, 80, 30);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Traditional from Indonesia");
        panelJaket.add(jLabel34);
        jLabel34.setBounds(660, 770, 170, 40);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("Traditional from Indonesia");
        panelJaket.add(jLabel35);
        jLabel35.setBounds(360, 420, 170, 40);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("Traditional from Indonesia");
        panelJaket.add(jLabel36);
        jLabel36.setBounds(80, 420, 170, 40);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Traditional from Indonesia");
        panelJaket.add(jLabel37);
        jLabel37.setBounds(80, 770, 170, 40);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Traditional from Indonesia");
        panelJaket.add(jLabel38);
        jLabel38.setBounds(370, 770, 170, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJaketActionPerformed
        // TODO add your handling code here:
        Desain desain = new Desain();
        desain.getTabbedPane().setSelectedIndex(1);
        desain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJaketActionPerformed

    private void dress4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dress4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dress4ActionPerformed

    private void dress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dress1ActionPerformed

    private void bayarDressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarDressActionPerformed
        // TODO add your handling code here:
        int total = 0;
        try {
            if (dress1.isSelected()) {
                int jumlah = Integer.parseInt(TFdress1.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 425000 * jumlah;
            }

            if (dress2.isSelected()) {
                int jumlah = Integer.parseInt(TFdress2.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 390000 * jumlah;
            }

            if (dress3.isSelected()) {
                int jumlah = Integer.parseInt(TFdress3.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 378000 * jumlah;
            }

            if (dress4.isSelected()) {
                int jumlah = Integer.parseInt(TFdress4.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 415000 * jumlah;
            }

            if (dress5.isSelected()) {
                int jumlah = Integer.parseInt(TFdress5.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 375000 * jumlah;
            }

            if (dress6.isSelected()) {
                int jumlah = Integer.parseInt(TFdress6.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 278000 * jumlah;
            }

            if (total == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih setidaknya satu harga dan jumlah produk!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Pembayaran pembayaran = new Pembayaran();
            pembayaran.setTotal("Rp " + total); 
            pembayaran.setVisible(true); 
            this.dispose();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah yang sesuai! " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bayarDressActionPerformed

    private void dress3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dress3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dress3ActionPerformed

    private void TFdress1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress1KeyTyped

    private void TFdress2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress2KeyTyped

    private void TFdress3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress3KeyTyped

    private void TFdress4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress4KeyTyped

    private void TFdress5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress5KeyTyped

    private void TFdress6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFdress6KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFdress6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dressNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dressNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dressNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dressNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dressNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFdress1;
    private javax.swing.JTextField TFdress2;
    private javax.swing.JTextField TFdress3;
    private javax.swing.JTextField TFdress4;
    private javax.swing.JTextField TFdress5;
    private javax.swing.JTextField TFdress6;
    private rojerusan.RSMaterialButtonRectangle backJaket;
    private rojerusan.RSMaterialButtonRectangle bayarDress;
    private javax.swing.JRadioButton dress1;
    private javax.swing.JRadioButton dress2;
    private javax.swing.JRadioButton dress3;
    private javax.swing.JRadioButton dress4;
    private javax.swing.JRadioButton dress5;
    private javax.swing.JRadioButton dress6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private untukpraktikum5.GradientRoundedPanel panelJaket;
    // End of variables declaration//GEN-END:variables
}
