/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Fadila Nur Habibah
 */
public class jaketNew extends javax.swing.JFrame {

    /**
     * Creates new form jaketNew
     */
    public jaketNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelJaket = new untukpraktikum5.GradientRoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        backJaket = new rojerusan.RSMaterialButtonRectangle();
        jaket2 = new javax.swing.JRadioButton();
        jaket4 = new javax.swing.JRadioButton();
        jaket1 = new javax.swing.JRadioButton();
        jaket6 = new javax.swing.JRadioButton();
        jaket3 = new javax.swing.JRadioButton();
        jaket5 = new javax.swing.JRadioButton();
        bayarJaket = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFjaket1 = new javax.swing.JTextField();
        TFjaket2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TFjaket3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        TFjaket4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        TFjaket5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TFjaket6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(903, 1563));

        panelJaket.setColorEnd(new java.awt.Color(153, 153, 255));
        panelJaket.setColorStart(new java.awt.Color(255, 153, 153));
        panelJaket.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket3.png"))); // NOI18N
        panelJaket.add(jLabel3);
        jLabel3.setBounds(630, 210, 190, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket6.png"))); // NOI18N
        panelJaket.add(jLabel4);
        jLabel4.setBounds(640, 560, 190, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket2.png"))); // NOI18N
        panelJaket.add(jLabel5);
        jLabel5.setBounds(350, 210, 190, 190);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket1.png"))); // NOI18N
        panelJaket.add(jLabel6);
        jLabel6.setBounds(70, 210, 190, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket4.png"))); // NOI18N
        panelJaket.add(jLabel7);
        jLabel7.setBounds(350, 560, 190, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionJaket/jaket5.png"))); // NOI18N
        panelJaket.add(jLabel8);
        jLabel8.setBounds(70, 560, 190, 190);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel9);
        jLabel9.setBounds(70, 420, 210, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Rp 225.000");
        panelJaket.add(jLabel12);
        jLabel12.setBounds(120, 450, 80, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel13);
        jLabel13.setBounds(350, 420, 200, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Rp 378.000");
        panelJaket.add(jLabel16);
        jLabel16.setBounds(680, 450, 80, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel17);
        jLabel17.setBounds(630, 420, 200, 40);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Rp 350.000");
        panelJaket.add(jLabel20);
        jLabel20.setBounds(130, 810, 90, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel21);
        jLabel21.setBounds(70, 780, 210, 30);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Rp 375.000");
        panelJaket.add(jLabel24);
        jLabel24.setBounds(410, 810, 100, 20);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel25);
        jLabel25.setBounds(350, 780, 210, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("Rp 278.000");
        panelJaket.add(jLabel28);
        jLabel28.setBounds(710, 810, 80, 20);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText(" Indonesian Traditional Clothes ");
        panelJaket.add(jLabel29);
        jLabel29.setBounds(650, 780, 200, 30);

        backJaket.setBackground(new java.awt.Color(0, 0, 102));
        backJaket.setText("B A C K");
        backJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJaketActionPerformed(evt);
            }
        });
        panelJaket.add(backJaket);
        backJaket.setBounds(150, 940, 240, 70);

        jaket2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket2.setText("Batik Jacket Merah Coksu");
        panelJaket.add(jaket2);
        jaket2.setBounds(310, 400, 270, 30);

        jaket4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket4.setText("Batik Jacket Biru Bunga");
        jaket4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaket4ActionPerformed(evt);
            }
        });
        panelJaket.add(jaket4);
        jaket4.setBounds(50, 750, 240, 30);

        jaket1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket1.setText("Batik Jacket Maroon Hitam");
        jaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaket1ActionPerformed(evt);
            }
        });
        panelJaket.add(jaket1);
        jaket1.setBounds(30, 400, 270, 30);

        jaket6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket6.setText("Batik Jacket Biru Cream");
        panelJaket.add(jaket6);
        jaket6.setBounds(620, 750, 240, 30);

        jaket3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket3.setText("Batik Jacket Hijau Cream");
        panelJaket.add(jaket3);
        jaket3.setBounds(590, 400, 260, 30);

        jaket5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaket5.setText("Batik Jacket Cream Bunga");
        panelJaket.add(jaket5);
        jaket5.setBounds(320, 750, 270, 30);

        bayarJaket.setBackground(new java.awt.Color(0, 0, 102));
        bayarJaket.setText("B A Y A R");
        bayarJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarJaketActionPerformed(evt);
            }
        });
        panelJaket.add(bayarJaket);
        bayarJaket.setBounds(490, 940, 240, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 60)); // NOI18N
        jLabel1.setText("BATIK JACKET");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(150, 50, 440, 110);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/home1.png"))); // NOI18N
        jPanel2.add(jLabel32);
        jLabel32.setBounds(570, 0, 210, 170);

        panelJaket.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 160);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("JUMLAH");
        panelJaket.add(jLabel10);
        jLabel10.setBounds(70, 480, 80, 30);

        TFjaket1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFjaket1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket1KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket1);
        TFjaket1.setBounds(160, 480, 90, 30);

        TFjaket2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket2KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket2);
        TFjaket2.setBounds(440, 480, 90, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("JUMLAH");
        panelJaket.add(jLabel14);
        jLabel14.setBounds(350, 480, 80, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("JUMLAH");
        panelJaket.add(jLabel18);
        jLabel18.setBounds(640, 480, 80, 30);

        TFjaket3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket3KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket3);
        TFjaket3.setBounds(730, 480, 90, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("JUMLAH");
        panelJaket.add(jLabel22);
        jLabel22.setBounds(80, 840, 80, 30);

        TFjaket4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket4KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket4);
        TFjaket4.setBounds(170, 840, 90, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("JUMLAH");
        panelJaket.add(jLabel26);
        jLabel26.setBounds(360, 840, 80, 30);

        TFjaket5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket5KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket5);
        TFjaket5.setBounds(450, 840, 90, 30);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("JUMLAH");
        panelJaket.add(jLabel30);
        jLabel30.setBounds(650, 840, 80, 30);

        TFjaket6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFjaket6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFjaket6KeyTyped(evt);
            }
        });
        panelJaket.add(TFjaket6);
        TFjaket6.setBounds(740, 840, 90, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Rp 320.000");
        panelJaket.add(jLabel33);
        jLabel33.setBounds(400, 450, 80, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJaketActionPerformed
        // TODO add your handling code here:
        Desain desain = new Desain();
        desain.getTabbedPane().setSelectedIndex(1);
        desain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJaketActionPerformed

    private void bayarJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarJaketActionPerformed
        // TODO add your handling code here:
        int total = 0;
        try {
            if (jaket1.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket1.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 225000 * jumlah;
            }

            if (jaket2.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket2.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 320000 * jumlah;
            }

            if (jaket3.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket3.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 378000 * jumlah;
            }

            if (jaket4.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket4.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 350000 * jumlah;
            }

            if (jaket5.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket5.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 375000 * jumlah;
            }

            if (jaket6.isSelected()) {
                int jumlah = Integer.parseInt(TFjaket6.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 278000 * jumlah;
            }

            if (total == 0) {
                JOptionPane.showMessageDialog(this, "Pilih setidaknya satu harga dan jumlah produk!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Pembayaran pembayaran = new Pembayaran();
            pembayaran.setTotal("Rp " + total); 
            pembayaran.setVisible(true); 
            this.dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah yang sesuai! " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bayarJaketActionPerformed

    private void jaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaket1ActionPerformed

    private void jaket4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaket4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaket4ActionPerformed

    private void TFjaket1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket1KeyTyped

    private void TFjaket1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TFjaket1KeyReleased

    private void TFjaket2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket2KeyTyped

    private void TFjaket3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket3KeyTyped

    private void TFjaket4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket4KeyTyped

    private void TFjaket5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket5KeyTyped

    private void TFjaket6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFjaket6KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFjaket6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jaketNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jaketNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jaketNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jaketNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jaketNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFjaket1;
    private javax.swing.JTextField TFjaket2;
    private javax.swing.JTextField TFjaket3;
    private javax.swing.JTextField TFjaket4;
    private javax.swing.JTextField TFjaket5;
    private javax.swing.JTextField TFjaket6;
    private rojerusan.RSMaterialButtonRectangle backJaket;
    private rojerusan.RSMaterialButtonRectangle bayarJaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jaket1;
    private javax.swing.JRadioButton jaket2;
    private javax.swing.JRadioButton jaket3;
    private javax.swing.JRadioButton jaket4;
    private javax.swing.JRadioButton jaket5;
    private javax.swing.JRadioButton jaket6;
    private untukpraktikum5.GradientRoundedPanel panelJaket;
    // End of variables declaration//GEN-END:variables
}
