/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fadila Nur Habibah
 */
public class LoginDanRegister extends javax.swing.JFrame {

    /**
     * Creates new form LoginDanRegister
     */
    public LoginDanRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        tabbedPaneCustom1 = new raven.tabbed.TabbedPaneCustom();
        panelLogin = new javax.swing.JPanel();
        panelLogin1 = new untukpraktikum5.GradientRoundedPanel();
        gambarLogin = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        TFuser = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        btnLogin = new rojerusan.RSMaterialButtonRectangle();
        panelRegister = new javax.swing.JPanel();
        panelRegister1 = new untukpraktikum5.GradientRoundedPanel();
        gambarRegis = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelUser2 = new javax.swing.JLabel();
        labelPass2 = new javax.swing.JLabel();
        labelConfir = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFuser2 = new javax.swing.JTextField();
        btnRegis = new rojerusan.RSMaterialButtonRectangle();
        Confir = new javax.swing.JPasswordField();
        Pass2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setBackground(new java.awt.Color(255, 255, 255));

        tabbedPaneCustom1.setBackground(new java.awt.Color(255, 204, 102));
        tabbedPaneCustom1.setSelectedColor(new java.awt.Color(0, 0, 102));

        panelLogin.setLayout(null);

        panelLogin1.setColorEnd(new java.awt.Color(204, 204, 255));
        panelLogin1.setColorStart(new java.awt.Color(255, 153, 153));
        panelLogin1.setLayout(null);

        gambarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginDanRegis/Login.png"))); // NOI18N
        panelLogin1.add(gambarLogin);
        gambarLogin.setBounds(130, 40, 169, 151);

        labelUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUser.setText("USERNAME");
        panelLogin1.add(labelUser);
        labelUser.setBounds(60, 240, 80, 30);

        labelPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPass.setText("PASSWORD");
        panelLogin1.add(labelPass);
        labelPass.setBounds(60, 300, 80, 30);

        TFuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelLogin1.add(TFuser);
        TFuser.setBounds(160, 240, 220, 30);

        Pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelLogin1.add(Pass);
        Pass.setBounds(160, 300, 220, 30);

        btnLogin.setBackground(new java.awt.Color(0, 0, 102));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin1.add(btnLogin);
        btnLogin.setBounds(160, 390, 220, 50);

        panelLogin.add(panelLogin1);
        panelLogin1.setBounds(0, 0, 450, 520);

        tabbedPaneCustom1.addTab("LOGIN", panelLogin);

        panelRegister1.setColorEnd(new java.awt.Color(204, 204, 255));
        panelRegister1.setColorStart(new java.awt.Color(255, 153, 153));
        panelRegister1.setLayout(null);

        gambarRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginDanRegis/Register.png"))); // NOI18N
        panelRegister1.add(gambarRegis);
        gambarRegis.setBounds(170, 40, 110, 120);

        labelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNama.setText("NAME");
        panelRegister1.add(labelNama);
        labelNama.setBounds(60, 180, 110, 30);

        labelUser2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUser2.setText("USERNAME");
        panelRegister1.add(labelUser2);
        labelUser2.setBounds(60, 230, 110, 30);

        labelPass2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPass2.setText("PASSWORD");
        panelRegister1.add(labelPass2);
        labelPass2.setBounds(60, 280, 110, 30);

        labelConfir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelConfir.setText("CONFIRM PASS");
        panelRegister1.add(labelConfir);
        labelConfir.setBounds(60, 330, 110, 30);

        TFnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegister1.add(TFnama);
        TFnama.setBounds(190, 180, 200, 30);

        TFuser2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegister1.add(TFuser2);
        TFuser2.setBounds(190, 230, 200, 30);

        btnRegis.setBackground(new java.awt.Color(0, 0, 102));
        btnRegis.setText("REGISTER");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        panelRegister1.add(btnRegis);
        btnRegis.setBounds(180, 400, 220, 50);

        Confir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegister1.add(Confir);
        Confir.setBounds(190, 330, 200, 30);

        Pass2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegister1.add(Pass2);
        Pass2.setBounds(190, 280, 200, 30);

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegister1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        tabbedPaneCustom1.addTab("REGISTER", panelRegister);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
        try {
            if (TFnama.getText().isEmpty() || TFuser2.getText().isEmpty() || 
                Pass2.getText().isEmpty() || Confir.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
                return;
            }

            if (!Pass2.getText().equals(Confir.getText())) {
                JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak cocok!");
                return;
            }

            String sqlRegister = "INSERT INTO register (nama, username, password, confir) VALUES (?, ?, ?, ?)";
            String sqlLogin = "INSERT INTO login (username, password) VALUES (?, ?)";

            java.sql.Connection conn = (java.sql.Connection) Koneksi.getKoneksi();

            java.sql.PreparedStatement pstRegis = conn.prepareStatement(sqlRegister);  
            pstRegis.setString(1, TFnama.getText());
            pstRegis.setString(2, TFuser2.getText()); 
            pstRegis.setString(3, Pass2.getText());  
            pstRegis.setString(4, Confir.getText()); 
            pstRegis.executeUpdate();

            java.sql.PreparedStatement pstLogin = conn.prepareStatement(sqlLogin);
            pstLogin.setString(1, TFuser2.getText()); 
            pstLogin.setString(2, Pass2.getText());   
            pstLogin.executeUpdate();

            JOptionPane.showMessageDialog(null, "Register Berhasil!");

            reset();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Register Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRegisActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            if (TFuser.getText().isEmpty() || Pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
                return;
            }

            String sql = "SELECT username FROM login WHERE username = ? AND password = ?";
            java.sql.Connection conn = (java.sql.Connection) Koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, TFuser.getText()); 
            pst.setString(2, Pass.getText());   

            java.sql.ResultSet res = pst.executeQuery();

            if (res.next()) {
            String loggedInUser = res.getString("username");

            JOptionPane.showMessageDialog(this, "Berhasil Login!");
            this.setVisible(false); 
            
            Home homePage = new Home();
            homePage.setWelcomeMessage(loggedInUser);
            homePage.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Username atau Password salah!");
        }

        reset();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Login Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void reset(){
        TFuser.setText("");
        Pass.setText("");
        
        TFnama.setText("");
        TFuser2.setText("");
        Pass2.setText("");
        Confir.setText(""); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDanRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDanRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDanRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDanRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDanRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confir;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField Pass2;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFuser;
    private javax.swing.JTextField TFuser2;
    private rojerusan.RSMaterialButtonRectangle btnLogin;
    private rojerusan.RSMaterialButtonRectangle btnRegis;
    private javax.swing.JLabel gambarLogin;
    private javax.swing.JLabel gambarRegis;
    private javax.swing.JLabel labelConfir;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPass2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser2;
    private javax.swing.JPanel panelLogin;
    private untukpraktikum5.GradientRoundedPanel panelLogin1;
    private javax.swing.JPanel panelRegister;
    private untukpraktikum5.GradientRoundedPanel panelRegister1;
    private javax.swing.JPanel panelUtama;
    private raven.tabbed.TabbedPaneCustom tabbedPaneCustom1;
    // End of variables declaration//GEN-END:variables
}
