/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Fadila Nur Habibah
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        TFtotal.setEditable(false);
    }
    
    public void setTotal(String total) {
        TFtotal.setText(total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavyBayar = new javax.swing.JPanel();
        panelDataBayar1 = new untukpraktikum5.GradientRoundedPanel();
        labelData1 = new javax.swing.JLabel();
        labelNamaData1 = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelTlp1 = new javax.swing.JLabel();
        TFnamaData1 = new javax.swing.JTextField();
        TFalamat1 = new javax.swing.JTextField();
        TFtlp1 = new javax.swing.JTextField();
        panelCashBayar = new untukpraktikum5.GradientRoundedPanel();
        labelProsesBayar = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelCash = new javax.swing.JLabel();
        labelPembayaran = new javax.swing.JLabel();
        TFcash = new javax.swing.JTextField();
        TFtotal = new javax.swing.JTextField();
        CBmetodeBayar = new javax.swing.JComboBox<>();
        btnBayar = new rojerusan.RSMaterialButtonRectangle();
        labelJudulBayar1 = new javax.swing.JLabel();
        labelJudulBayar2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavyBayar.setBackground(new java.awt.Color(255, 255, 255));
        panelNavyBayar.setLayout(null);

        panelDataBayar1.setColorEnd(new java.awt.Color(255, 204, 255));
        panelDataBayar1.setColorStart(new java.awt.Color(255, 102, 102));
        panelDataBayar1.setLayout(null);

        labelData1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelData1.setText("Lengkapi Data Anda!");
        panelDataBayar1.add(labelData1);
        labelData1.setBounds(140, 50, 250, 40);

        labelNamaData1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNamaData1.setText("NAMA");
        panelDataBayar1.add(labelNamaData1);
        labelNamaData1.setBounds(50, 130, 80, 30);

        labelAlamat1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAlamat1.setText("ALAMAT");
        panelDataBayar1.add(labelAlamat1);
        labelAlamat1.setBounds(50, 200, 80, 30);

        labelTlp1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTlp1.setText("TELEPON");
        panelDataBayar1.add(labelTlp1);
        labelTlp1.setBounds(50, 270, 80, 30);

        TFnamaData1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDataBayar1.add(TFnamaData1);
        TFnamaData1.setBounds(180, 130, 270, 30);

        TFalamat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelDataBayar1.add(TFalamat1);
        TFalamat1.setBounds(180, 200, 270, 30);

        TFtlp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFtlp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFtlp1KeyTyped(evt);
            }
        });
        panelDataBayar1.add(TFtlp1);
        TFtlp1.setBounds(180, 270, 270, 30);

        panelNavyBayar.add(panelDataBayar1);
        panelDataBayar1.setBounds(0, 190, 510, 640);

        panelCashBayar.setColorEnd(new java.awt.Color(255, 204, 255));
        panelCashBayar.setColorStart(new java.awt.Color(153, 153, 255));
        panelCashBayar.setLayout(null);

        labelProsesBayar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProsesBayar.setText("---- Proses Pembayaran ----");
        panelCashBayar.add(labelProsesBayar);
        labelProsesBayar.setBounds(100, 50, 330, 40);

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotal.setText("TOTAL");
        panelCashBayar.add(labelTotal);
        labelTotal.setBounds(40, 130, 120, 30);

        labelCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCash.setText("CASH");
        panelCashBayar.add(labelCash);
        labelCash.setBounds(40, 200, 120, 30);

        labelPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPembayaran.setText(" PEMBAYARAN");
        panelCashBayar.add(labelPembayaran);
        labelPembayaran.setBounds(40, 270, 140, 25);

        TFcash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFcash.setText("Rp ");
        TFcash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFcashKeyTyped(evt);
            }
        });
        panelCashBayar.add(TFcash);
        TFcash.setBounds(210, 200, 240, 30);

        TFtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelCashBayar.add(TFtotal);
        TFtotal.setBounds(210, 130, 240, 30);

        CBmetodeBayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBmetodeBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Metode Pembayaran --", "Dana", "Ovo", "Gopay", "Flip", "LinkAja" }));
        panelCashBayar.add(CBmetodeBayar);
        CBmetodeBayar.setBounds(210, 270, 240, 30);

        btnBayar.setBackground(new java.awt.Color(0, 0, 102));
        btnBayar.setText("B A Y A R");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        panelCashBayar.add(btnBayar);
        btnBayar.setBounds(210, 380, 240, 60);

        panelNavyBayar.add(panelCashBayar);
        panelCashBayar.setBounds(540, 190, 500, 650);

        labelJudulBayar1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        labelJudulBayar1.setForeground(new java.awt.Color(255, 153, 153));
        labelJudulBayar1.setText("BAYAR AMAN,");
        panelNavyBayar.add(labelJudulBayar1);
        labelJudulBayar1.setBounds(310, 20, 420, 60);

        labelJudulBayar2.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        labelJudulBayar2.setForeground(new java.awt.Color(153, 153, 255));
        labelJudulBayar2.setText("BELANJA TENANG");
        panelNavyBayar.add(labelJudulBayar2);
        labelJudulBayar2.setBounds(250, 80, 540, 60);

        getContentPane().add(panelNavyBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here: 
        try {
            if (TFnamaData1.getText().isEmpty() || TFalamat1.getText().isEmpty() || TFtlp1.getText().isEmpty() 
                || TFtotal.getText().isEmpty() || TFcash.getText().isEmpty() || CBmetodeBayar.getSelectedItem() == null 
                || CBmetodeBayar.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Harap lengkapi semua data dan pilih metode pembayaran yang valid!");
                return; 
            }

            String totalInput = TFtotal.getText().replaceAll("[^0-9]", ""); 
            String cashInput = TFcash.getText().replaceAll("[^0-9]", "");   

            int total = Integer.parseInt(totalInput); 
            int cash = Integer.parseInt(cashInput);   

            if (cash < total) {
                JOptionPane.showMessageDialog(null, "Uang anda tidak mencukupi!");
                return;
            } else if (cash > total) {
                JOptionPane.showMessageDialog(null, "Masukkan cash sesuai total belanja!");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin membeli?", "Konfirmasi Pembayaran", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String metodePembayaran = CBmetodeBayar.getSelectedItem().toString();
                String sql = "INSERT INTO riwayat1 (nama, alamat, telepon, total, cash, metode) VALUES (?, ?, ?, ?, ?, ?)";
                java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, TFnamaData1.getText());
                pst.setString(2, TFalamat1.getText());
                pst.setString(3, TFtlp1.getText());
                pst.setInt(4, total); 
                pst.setInt(5, cash); 
                pst.setString(6, metodePembayaran);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Pembayaran berhasil");
                load_data(); 
                kosong();    
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void TFcashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFcashKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFcashKeyTyped

    private void TFtlp1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtlp1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFtlp1KeyTyped

    private void load_data() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No"); 
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        model.addColumn("Total");
        model.addColumn("Cash");
        model.addColumn("Metode Pembayaran");

        try {
            String sql = "SELECT * FROM riwayat1";
            java.sql.Connection conn = (Connection) Koneksi.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            int no = 1; 
            while (res.next()) {
                model.addRow(new Object[]{
                    no++, 
                    res.getString("nama"),
                    res.getString("alamat"),
                    res.getString("telepon"),
                    res.getString("total"),
                    res.getString("cash"),
                    res.getString("metode")
                });
            }

            Desain frameDesain = new Desain();
            frameDesain.getTabbedPane().setSelectedIndex(2); 
            frameDesain.getTabelPelanggan().setModel(model); 
            frameDesain.setVisible(true); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error memuat data: " + e.getMessage());
        }
    }




    
    private void kosong(){
        TFnamaData1.setText("");
        TFalamat1.setText("");
        TFtlp1.setText("");
        TFtotal.setText("");
        TFcash.setText("");
        CBmetodeBayar.setSelectedIndex(0);
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBmetodeBayar;
    private javax.swing.JTextField TFalamat1;
    private javax.swing.JTextField TFcash;
    private javax.swing.JTextField TFnamaData1;
    private javax.swing.JTextField TFtlp1;
    public javax.swing.JTextField TFtotal;
    private rojerusan.RSMaterialButtonRectangle btnBayar;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelData1;
    private javax.swing.JLabel labelJudulBayar1;
    private javax.swing.JLabel labelJudulBayar2;
    private javax.swing.JLabel labelNamaData1;
    private javax.swing.JLabel labelPembayaran;
    private javax.swing.JLabel labelProsesBayar;
    private javax.swing.JLabel labelTlp1;
    private javax.swing.JLabel labelTotal;
    private untukpraktikum5.GradientRoundedPanel panelCashBayar;
    private untukpraktikum5.GradientRoundedPanel panelDataBayar1;
    private javax.swing.JPanel panelNavyBayar;
    // End of variables declaration//GEN-END:variables
}
