/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.event.KeyEvent;

/**
 *
 * @author Fadila Nur Habibah
 */
public class vestNew extends javax.swing.JFrame {

    /**
     * Creates new form vestNew
     */
    public vestNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelJaket = new untukpraktikum5.GradientRoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backJaket = new rojerusan.RSMaterialButtonRectangle();
        bayarVest = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        vest1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        TFvest1 = new javax.swing.JTextField();
        vest2 = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        TFvest2 = new javax.swing.JTextField();
        vest3 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        TFvest3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        vest4 = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        TFvest4 = new javax.swing.JTextField();
        vest5 = new javax.swing.JRadioButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        TFvest5 = new javax.swing.JTextField();
        vest6 = new javax.swing.JRadioButton();
        jLabel54 = new javax.swing.JLabel();
        TFvest6 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(903, 1563));

        panelJaket.setColorEnd(new java.awt.Color(153, 153, 255));
        panelJaket.setColorStart(new java.awt.Color(255, 153, 153));
        panelJaket.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest5.png"))); // NOI18N
        panelJaket.add(jLabel3);
        jLabel3.setBounds(350, 560, 190, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest6.png"))); // NOI18N
        panelJaket.add(jLabel4);
        jLabel4.setBounds(640, 560, 190, 190);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest2.png"))); // NOI18N
        panelJaket.add(jLabel5);
        jLabel5.setBounds(350, 210, 190, 190);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest1.png"))); // NOI18N
        panelJaket.add(jLabel6);
        jLabel6.setBounds(70, 210, 190, 190);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest3.png"))); // NOI18N
        panelJaket.add(jLabel7);
        jLabel7.setBounds(630, 210, 190, 190);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FashionVest/vest4.png"))); // NOI18N
        panelJaket.add(jLabel8);
        jLabel8.setBounds(70, 560, 190, 190);

        backJaket.setBackground(new java.awt.Color(0, 0, 102));
        backJaket.setText("B A C K");
        backJaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJaketActionPerformed(evt);
            }
        });
        panelJaket.add(backJaket);
        backJaket.setBounds(150, 920, 240, 70);

        bayarVest.setBackground(new java.awt.Color(0, 0, 102));
        bayarVest.setText("B A Y A R");
        bayarVest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarVestActionPerformed(evt);
            }
        });
        panelJaket.add(bayarVest);
        bayarVest.setBounds(490, 920, 240, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 60)); // NOI18N
        jLabel1.setText("BATIK VEST");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(240, 40, 390, 110);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/home1.png"))); // NOI18N
        jPanel2.add(jLabel32);
        jLabel32.setBounds(570, 0, 210, 170);

        panelJaket.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 160);

        vest1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest1.setText("Batik Vest Biru");
        vest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest1ActionPerformed(evt);
            }
        });
        panelJaket.add(vest1);
        vest1.setBounds(80, 400, 160, 30);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel33);
        jLabel33.setBounds(590, 420, 260, 40);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("Rp 390.000");
        panelJaket.add(jLabel34);
        jLabel34.setBounds(120, 450, 90, 30);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setText("JUMLAH");
        panelJaket.add(jLabel36);
        jLabel36.setBounds(70, 480, 80, 30);

        TFvest1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest1KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest1);
        TFvest1.setBounds(160, 480, 90, 30);

        vest2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest2.setText("Batik Vest Cream Merah");
        vest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest2ActionPerformed(evt);
            }
        });
        panelJaket.add(vest2);
        vest2.setBounds(320, 400, 240, 30);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("Rp 280.000");
        panelJaket.add(jLabel38);
        jLabel38.setBounds(400, 450, 90, 30);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setText("JUMLAH");
        panelJaket.add(jLabel40);
        jLabel40.setBounds(350, 480, 80, 30);

        TFvest2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest2KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest2);
        TFvest2.setBounds(440, 480, 90, 30);

        vest3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest3.setText("Batik Vest Hitam Merah ");
        vest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest3ActionPerformed(evt);
            }
        });
        panelJaket.add(vest3);
        vest3.setBounds(600, 400, 260, 30);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setText("Rp 250.000");
        panelJaket.add(jLabel42);
        jLabel42.setBounds(680, 450, 90, 30);

        TFvest3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest3KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest3);
        TFvest3.setBounds(720, 480, 90, 30);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel44.setText("JUMLAH");
        panelJaket.add(jLabel44);
        jLabel44.setBounds(630, 480, 80, 30);

        vest4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest4.setText("Batik Vest Merah Motif");
        vest4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest4ActionPerformed(evt);
            }
        });
        panelJaket.add(vest4);
        vest4.setBounds(50, 760, 240, 30);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setText("Rp 350.000");
        panelJaket.add(jLabel46);
        jLabel46.setBounds(130, 810, 90, 30);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel48.setText("JUMLAH");
        panelJaket.add(jLabel48);
        jLabel48.setBounds(70, 840, 80, 30);

        TFvest4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest4KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest4);
        TFvest4.setBounds(160, 840, 90, 30);

        vest5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest5.setText("Batik Vest Merah");
        vest5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest5ActionPerformed(evt);
            }
        });
        panelJaket.add(vest5);
        vest5.setBounds(350, 760, 180, 30);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setText("Rp 200.000");
        panelJaket.add(jLabel50);
        jLabel50.setBounds(410, 810, 90, 30);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel52.setText("JUMLAH");
        panelJaket.add(jLabel52);
        jLabel52.setBounds(350, 840, 80, 30);

        TFvest5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest5KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest5);
        TFvest5.setBounds(440, 840, 90, 30);

        vest6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vest6.setText("Batik Vest Hitam Motif Bunga");
        vest6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vest6ActionPerformed(evt);
            }
        });
        panelJaket.add(vest6);
        vest6.setBounds(580, 760, 290, 30);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel54.setText("Rp 370.000");
        panelJaket.add(jLabel54);
        jLabel54.setBounds(690, 810, 90, 30);

        TFvest6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TFvest6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFvest6KeyTyped(evt);
            }
        });
        panelJaket.add(TFvest6);
        TFvest6.setBounds(720, 840, 90, 30);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel56.setText("JUMLAH");
        panelJaket.add(jLabel56);
        jLabel56.setBounds(630, 840, 80, 30);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel37);
        jLabel37.setBounds(30, 420, 260, 40);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel43);
        jLabel43.setBounds(310, 420, 260, 40);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel45.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel45);
        jLabel45.setBounds(40, 790, 260, 30);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel49);
        jLabel49.setBounds(320, 790, 260, 30);

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel55.setText("Vest Blazer Batik Pattern from Indonesia ");
        panelJaket.add(jLabel55);
        jLabel55.setBounds(600, 790, 260, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vest6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest6ActionPerformed

    private void vest5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest5ActionPerformed

    private void vest4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest4ActionPerformed

    private void vest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest3ActionPerformed

    private void vest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest2ActionPerformed

    private void vest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vest1ActionPerformed

    private void bayarVestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarVestActionPerformed
        // TODO add your handling code here:
        int total = 0;
        try {
            if (vest1.isSelected()) {
                int jumlah = Integer.parseInt(TFvest1.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 390000 * jumlah;
            }

            if (vest2.isSelected()) {
                int jumlah = Integer.parseInt(TFvest2.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 280000 * jumlah;
            }

            if (vest3.isSelected()) {
                int jumlah = Integer.parseInt(TFvest3.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 250000 * jumlah;
            }

            if (vest4.isSelected()) {
                int jumlah = Integer.parseInt(TFvest4.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 350000 * jumlah;
            }

            if (vest5.isSelected()) {
                int jumlah = Integer.parseInt(TFvest5.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 200000 * jumlah;
            }

            if (vest6.isSelected()) {
                int jumlah = Integer.parseInt(TFvest6.getText());
                if (jumlah <= 0) {
                    throw new NumberFormatException("Jumlah jaket harus lebih dari nol.");
                }
                total += 370000 * jumlah;
            }

            if (total == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih setidaknya satu harga dan jumlah produk!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            Pembayaran pembayaran = new Pembayaran();
            pembayaran.setTotal("Rp " + total); 
            pembayaran.setVisible(true); 
            this.dispose();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan jumlah yang sesuai! " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bayarVestActionPerformed

    private void backJaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJaketActionPerformed
        // TODO add your handling code here:
        Desain desain = new Desain();
        desain.getTabbedPane().setSelectedIndex(1);
        desain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJaketActionPerformed

    private void TFvest1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest1KeyTyped

    private void TFvest2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest2KeyTyped

    private void TFvest3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest3KeyTyped

    private void TFvest4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest4KeyTyped

    private void TFvest5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest5KeyTyped

    private void TFvest6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFvest6KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)){
           evt.consume(); 
        }
    }//GEN-LAST:event_TFvest6KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vestNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vestNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vestNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vestNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vestNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFvest1;
    private javax.swing.JTextField TFvest2;
    private javax.swing.JTextField TFvest3;
    private javax.swing.JTextField TFvest4;
    private javax.swing.JTextField TFvest5;
    private javax.swing.JTextField TFvest6;
    private rojerusan.RSMaterialButtonRectangle backJaket;
    private rojerusan.RSMaterialButtonRectangle bayarVest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private untukpraktikum5.GradientRoundedPanel panelJaket;
    private javax.swing.JRadioButton vest1;
    private javax.swing.JRadioButton vest2;
    private javax.swing.JRadioButton vest3;
    private javax.swing.JRadioButton vest4;
    private javax.swing.JRadioButton vest5;
    private javax.swing.JRadioButton vest6;
    // End of variables declaration//GEN-END:variables
}
